# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -anton14024@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="816f54a7-aafb-4e1d-b7ff-9ba6943b0bdd"